version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - devops
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - devops
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/tasks

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - devops
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

networks:
  devops:
    driver: bridge

volumes:
  mongo_data: